### ISSUE TITLE
Problem at Linux: thread 'main' panicked...

### ISSUE THREAD

**Issue by UffeJakobsen** [SebastianAbel/sidbang64#1]
Hi,

Tried to build the latest source (340689c910c61c581790626ef9fc15b178beff60)

The windows is displaying its frame in much less that a second - and I get this backtrace - see below

I'm running ArchLinux (@x86_64)  (LXQt Desktop environment) 

```
% RUST_BACKTRACE=1  target/release/sidbang64                                                                                                          [17:31:56]
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /build/rust/src/rustc-1.49.0-src/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.49.0-src/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.49.0-src/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /build/rust/src/rustc-1.49.0-src/library/core/src/panicking.rs:50:5
   3: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
   4: winit::platform::platform::x11::EventsLoop::process_event
   5: sidbang64::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
zsh: exit 101   RUST_BACKTRACE=1 target/release/sidbang64
```

**Comment by SebastianAbel** [comment]
Please could you build a debug version (cargo build) and run target/debug/sidbang64.
That crashlog should help identifying the issue. Maybe set RUST_BACKTRACE=full.

Thank you. The help is appreciated.

**Comment by SebastianAbel** [comment]
Looks like i need to update some more dependencies to work with current rustc 1.49.0. I was still on 1.45
In the meantime a workaround could be downgrading rust via rustup:
rustup install 1.45.0
rustup default 1.45.0

Solution found at https://medium.com/journey-to-rust/a-sad-bit-of-rust-lore-cc5403da5626
